name: Keploy

on:
  pull_request:
  push:

jobs:
  node_linux:
    runs-on: ubuntu-latest
    environment: secrets  # Ensure you specify the environment if it's an environment-level secret
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        mkdir -p $HOME/.docker/cli-plugins
        curl -L "https://github.com/docker/compose/releases/download/v2.6.1/docker-compose-linux-x86_64" -o $HOME/.docker/cli-plugins/docker-compose
        chmod +x $HOME/.docker/cli-plugins/docker-compose
        echo "$HOME/.docker/cli-plugins" >> $GITHUB_PATH
        docker-compose --version

    - name: Install python
      uses: actions/setup-python@v4
      with:
          python-version: 3.11.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage

    - name: Run the python-fastapi template
      run: |
        chmod +x ${GITHUB_WORKSPACE}/.github/workflows/test_workflows/keploy.sh
        ${GITHUB_WORKSPACE}/.github/workflows/test_workflows/keploy.sh
      env:
        GITHUB_TOKEN: ${{ secrets.SECRETS }}

    # - name: Upload coverage to Codecov
    #   uses: codecov/codecov-action@v2
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}
    #     files: ./coverage/lcov.info
    #     verbose: true
